### ISSUE TITLE
Convert Jenkins file from Windows Batch to Linux sh/bash

### ISSUE THREAD

**Issue by marcionemec-daitan** [bcgov/nr-spar-data-sync#27]
**Situation:** 

While trying to build/deploy the Vault issue solution (see #17  issue), Jenkins Cron server raised error trying to connect in github.com. This error is impeditive to deploy the pipeline of the project. 

Asking to 1Team for a guidance, the team suggested us to use the Jenkins [Polaris server:](Polaris Jenkins: https://apps.nrs.gov.bc.ca/int/confluence/display/1TEAM/Polaris+Jenkins) 

**Background:**

Jenkins Cron is based in a Windows System, so, Jenkins file pipeline configuration uses the "Windows batch" command. But Jenkins Polaris is based in a Linux system, so pipeline configuration needs to be handled using sh/bash commands. 

**Analysis:**

Rewrite Pipeline code in Jenkins_Cron jenkins file to a new linux-based Jenkins file Jenkins_Polaris.

**Comment by craigyu** [comment]
rolled over from Sprint 24

**Comment by marcionemec-daitan** [comment]
Issue solved: 

See: https://cd.io.nrs.gov.bc.ca/job/spar/job/DataSyncEngine/12/console for more details.

**Comment by marcionemec-daitan** [comment]
Solved. Documentation will be handled in #26 issue
