### ISSUE TITLE
DSE Deployment - Pass credentials gathered through Vault into Podman DSE instance

### ISSUE THREAD

**Issue by marcionemec-daitan** [bcgov/nr-spar-data-sync#30]
**Issue:** Database credentials needs to be handled by a secrets engine (Vault) to be injected in the Source Code of Data Sync Engine in Run Time execution, avoiding data leakage. 

**Background:**  Vault access was configured in Jenkins Cron server, but needs to be implemented in the Jenkins Polaris architecture, using podman containerized application. 

List of base documentation to implement:
- Source code sample: https://github.com/bcgov-nr/polaris-pipelines/blob/main/pipelines/shared/Jenkinsfile
- Polaris Jenkins 1Team documentation: https://apps.nrs.gov.bc.ca/int/confluence/display/1TEAM/Polaris+Jenkins
- Polaris Shared Library: https://apps.nrs.gov.bc.ca/int/confluence/display/1TEAM/Polaris+Shared+Library

**Acceptance Criteria:** 

1: Sample Dummy code retrieving data from Vault and checking if K/V are expected.
2: Documentation in Confluence Page.

** Ticket Reference **

This ticked blocks Issue #17 as database credentials are stored in Vault, so first is needed to implement a vault access to Jenkins Polaris execution instance.

**Comment by SLDonnelly** [comment]
@marcionemec-daitan you can reach out to Andreas Wilson and Grace Ruan from 1Team for assistance resolving this issue

CC: @macarrig
