### ISSUE TITLE
[Data Sync] Adapt engine to run on Jenkins

### ISSUE THREAD

**Issue by thiagosanchezenc** [bcgov/nr-spar-data-sync#5]
Adapt the engine created so it can run on a Jenkins server.

Definition of done:
- Documentation on Confluence
- Source code delivered;

**Comment by thiagosanchezenc** [comment]
This issue is blocked due to a couple of reasons:
- We still do not have proper access to Jenkins environment;
- The testing database is not yet properly set (final tables created) and there is no data available to test the sync process;
- We just found out that other teams that were supposedly running their automated data extraction on Jenkins are actually running the process on an Emerald cluster on OpenShift using Docker;
It seems to be a better approach to run it on OpenShift instead of Jenkins, further investigation needs to be addressed.

**Comment by marcionemec-daitan** [comment]
Some updates so far:

1) Already got access to Jenkins Cron (link at: https://apps.nrs.gov.bc.ca/int/cron/me/my-views/view/all/job/SPAR/)

2) Jenkins Cron is under Windows OS, so, all tests done in the Unix-like environments must be "translated" to be executed in Windows (i.e. "bat scripts instead sh/bash")

3) To start a spike in a OpenShift we will need access to use a dev/stage environment to set up a plan to deploy a docker containerized data sync engine.

**Comment by marcionemec-daitan** [comment]
This issue is blocked by:


![Image](https://github.com/bcgov/nr-spar-data-sync/assets/83302904/70e809b3-ae34-416f-bda2-6eb99209b8a7)

This error happens when we tried to deploy a Data Sync engine instance running in Jenkins Cron server. 
We would need some help from the Jenkins Admins to allow github BCGOV repository to be accessed by git scm on Jenkins cron.

**Comment by marcionemec-daitan** [comment]
Issue with proxy access solved using the following parameters in the Jenkins Config:



![Image](https://github.com/bcgov/nr-spar-data-sync/assets/83302904/0ddf5963-de37-4594-a563-f5dc7113c946)

**Comment by marcionemec-daitan** [comment]
Documentation can be found at: https://apps.nrs.gov.bc.ca/int/confluence/display/FSADT2/Jenkins+configuration

**Comment by marcionemec-daitan** [comment]
PR opened at: https://github.com/bcgov/nr-spar-data-sync/pull/18
